
            var ids= ["P1",
    "P2",
    "P3",
    "P4",
    "P5",
    "P6",
    "P7",
    "P8",
    "P9",
    "P10",
    "P11",
    "P12",
    "P13",
    "P14",
    "P15",
    "P16",
    "P17",
    "P18",
    "P19",
    "P20",
    "P21",
    "P22",
    "P23",
    "P24",
    "P25",
    "P26",
    "P27",
    "P28",
    "P29",
    "P30",
    "P31",
    "P32",
    "P33",
    "P34",
    "P35",
    "P36",
    "P37",
    "P38",
    "P39",
    "P40",
    "P41",
    "P42",
    "P43",
    "P44",
    "P45",
    "P46",
    "P47",
    "P48",
    "P49",
    "P50",
    "P51",
    "P52",
    "P53",
    "P54",
    "P55",
    "P56",
    "P57",
    "P58",
    "P59",
    "P60",
    "P61",
    "P62",
    "P63",
    "P64",
    "P65",
    "P66",
    "P67",
    "P68",
    "P69",
    "P70",
    "P71",
    "P72",
    "P73",
    "P74",
    "P75",
    "P76",
    "P77",
    "P78",
    "P79",
    "P80",
    "P81",
    "P82",
    "P83",
    "P84",
    "P85",
    "P86",
    "P87",
    "P88",
    "P89",
    "P90",
    "P91",
    "P92",
    "P93",
    "P94",
    "P95",
    ];
            var nomes=["ALVARO JOSE DE CASTRO MOREIRA DA SILVA",
    "ANDRE FILIPE AZEVEDO SOUSA",
    "BRUNO MIGUEL PEREIRA PINTO",
    "FILIPE ALEXANDRE DA SILVA MARTINS",
    "HELDER RICARDO DIAS RIBEIRO",
    "HERNANI RODRIGUES DA SILVA",
    "JORGE MANUEL BARROS NUNES",
    "JOSE MIGUEL ARAUJO FERREIRA",
    "PEDRO GABRIEL DIAS FERREIRA",
    "PEDRO MANUEL VIEIRA SANTOS PINTO",
    "RUI MANUEL AFONSO RODRIGUES SILVA GUERRA",
    "SERGIO MIGUEL VALENTE DE ALMEIDA",
    "TIAGO MACHADO SILVA",
    "VASCO DUARTE ALMEIDA DIAS DE CASTRO",
    "ANTONIO JOSE OLIVEIRA FARIA",
    "CARLA MARIA MENDES DE CASTRO",
    "MARLENE AZEVEDO DA SILVA",
    "PAULO ALEXANDRE MARQUES DE OLIVEIRA SERAFIM",
    "DAVID FILIPE OLIVEIRA COSTA",
    "RICARDO MIGUEL CARVALHO FERREIRA",
    "JOSE ALVES DE CASTRO",
    "MARIO BENTO BRITO NOBREGA RAMOS DE AZEVEDO",
    "PAULO CESAR RODRIGUES GOMES",
    "Susana Pereira",
    "Gabriel Reis",
    "Arsénio",
    "Frederico Pinto",
    "Gonçalo Hermenegildo",
    "Luis",
    "Miguel Pinto",
    "Pedro Lopes",
    "António José Coutinho Barbosa",
    "Ricardo Paz",
    "Sandrina Maciel",
    "Bruno Martins",
    "Filipe Froufe",
    "João Brites",
    "Leandro Morgado",
    "Manuel Sousa",
    "Pedro Resende",
    "Ricardo",
    "Fernanda Barroso",
    "Marta Silva",
    "Paulo Alexandre Afonso Dias",
    "Susana Pacheco",
    "Almeno",
    "Carlos Durana",
    "Hernani Silva",
    "Sofia PAiva",
    "Bruno Miguel Pereira Pinto",
    "Cristiano Cunha",
    "Daniel Pires",
    "Ernesto Miranda Pedrosa da Silva",
    "Manuel Joao Salgado da Costa Amaro",
    "Pedro Nuno Tavares da Silva ",
    "Rui Pedro da Costa Barbosa",
    "Carlos Guilherme Pelaio Macedo Costa ",
    "Jorge Filipe Marcos Mota ",
    "Nuno Miguel Alves Peixoto",
    "Vânia Sifia Carvalho",
    "Maria Campos",
    "Nuno Rodrigues",
    "Adélio Marco da Costa Fernandes",
    "Alexandre Gonçalves",
    "Amândio Telmo Oliveira Teixeira",
    "Carla Sofia de Almeida Coutinho ",
    "Edison Oliveira",
    "Fernando Sousa",
    "Filipe Manuel Alves Romano",
    "Francisco Alexandre Aires Gonçalves",
    "Mário André de Castro Vila Cova",
    "Nuno Santos",
    "Nuno Miguel dos Santos Nunes Roldão",
    "Orlando Jorge Carvalho Ribeiro",
    "Pedro Filipe Meira Morais",
    "Renato Neves",
    "Ricardo",
    "Ricardo Manuel da Silva Abreu",
    "Rui Miguel Silva",
    "Sandro Miguel Vales de Freitas",
    "Ana Luísa Pinto Teixeira",
    "Cândida",
    "Carla Susana Teixeira",
    "Daniel Edgar Pinto Soares",
    "Lúcia Sofia Miranda",
    "Márcio Ferreira",
    "Maria da Conceição Mota",
    "Maria João Fernandes Guerreiro da Silva ",
    "Miguel Carreira",
    "Vítor Manuel Catarino",
    "Vitor Gonçalves",
    "Fernando Jorge Ferreira Laúndos da Costa",
    "Marco Paulo Martins Cruz",
    "Miguel Pereira Mateus",
    "Rodney Lopes Gomes",
    ];
            var cursos = ["Curso Supletivo de Piano",
    "Curso Básico de Corne Inglês",
    "Curso Básico de Tuba",
    "Curso Básico de Bandolim",
    "Curso Supletivo de Fagote",
    "Curso Básico de Trompete",
    "Curso Básico de Saxofone",
    "Curso Supletivo de Tuba",
    "Curso Supletivo de Clarinete",
    "Curso Básico de Violoncelo",
    "Curso Supletivo de Saxofone",
    "Curso Básico de Orgão",
    "Curso Básico de Trompa",
    "Curso Básico de Trombone",
    "Curso Básico de Contrabaixo",
    "Curso Básico de Saxofone",
    "Curso Supletivo de Corne Inglês",
    "Curso Básico de Piano",
    "Curso Supletivo de Fliscorne",
    "Curso Básico de Piano",
    "Curso Básico de Trompa",
    "Curso Básico de Violoncelo",
    "Curso Básico de Viola de Arco",
    "Curso Supletivo de Percussão",
    "Curso Básico de Trompa",
    "Curso Básico de Clarinete",
    "Curso Básico de Harpa",
    "Curso Supletivo de Viola de Arco",
    "Curso Básico de Trombone",
    "Curso Básico de Orgão",
    "Curso Básico de Viola de Arco",
    "Curso Básico de Corne Inglês",
    "Curso Supletivo de Eufónio",
    "Curso Básico de Piano",
    "Curso Básico de Eufónio",
    "Curso Básico de Trompa",
    "Curso Supletivo de Oboé",
    "Curso Básico de Fagote",
    "Curso Básico de Guitarra",
    "Curso Básico de Trompa",
    "Curso Básico de Percussão",
    "Curso Supletivo de Contrabaixo",
    "Curso Básico de Tuba",
    "Curso Básico de Eufónio",
    "Curso Básico de Tuba",
    "Curso Básico de Piano",
    "Curso Básico de Violoncelo",
    "Curso Básico de Trompa",
    "Curso Supletivo de Oboé",
    "Curso Básico de Contrabaixo",
    "Curso Básico de Orgão",
    "Curso Básico de Fagote",
    "Curso Básico de Oboé",
    "Curso Básico de Oboé",
    "Curso Básico de Clarinete",
    "Curso Básico de Clarinete",
    "Curso Básico de Harpa",
    "Curso Básico de Flauta",
    "Curso Básico de Eufónio",
    "Curso Básico de Eufónio",
    "Curso Básico de Guitarra",
    "Curso Básico de Bandolim",
    "Curso Básico de Trompa",
    "Curso Básico de Contrabaixo",
    "Curso Básico de Fliscorne",
    "Curso Básico de Violino",
    "Curso Básico de Corne Inglês",
    "Curso Supletivo de Trompa",
    "Curso Supletivo de Flauta",
    "Curso Básico de Trombone",
    "Curso Básico de Piano",
    "Curso Básico de Percussão",
    "Curso Básico de Harpa",
    "Curso Básico de Flauta",
    "Curso Básico de Violino",
    "Curso Supletivo de Harpa",
    "Curso Básico de Violoncelo",
    "Curso Básico de Tuba",
    "Curso Básico de Corne Inglês",
    "Curso Básico de Harpa",
    "Curso Básico de Piano",
    "Curso Básico de Viola de Arco",
    "Curso Básico de Trompa",
    "Curso Básico de Violino",
    "Curso Básico de Clarinete",
    "Curso Básico de Fliscorne",
    "Curso Supletivo de Flauta",
    "Curso Básico de Saxofone",
    "Curso Básico de Trompa",
    "Curso Básico de Trombone",
    "Curso Básico de Harpa",
    "Curso Básico de Percussão",
    "Curso Básico de Fagote",
    "Curso Básico de Contrabaixo",
    "Curso Básico de Clarinete",
    ];
        