
            var cursos= ["Curso Básico de Clarinete",
    "Curso Supletivo de Clarinete",
    "Curso Básico de Contrabaixo",
    "Curso Supletivo de Contrabaixo",
    "Curso Básico de Corne Inglês",
    "Curso Supletivo de Corne Inglês",
    "Curso Básico de Eufónio",
    "Curso Supletivo de Eufónio",
    "Curso Básico de Fagote",
    "Curso Supletivo de Fagote",
    "Curso Básico de Flauta",
    "Curso Supletivo de Flauta",
    "Curso Básico de Fliscorne",
    "Curso Supletivo de Fliscorne",
    "Curso Básico de Guitarra",
    "Curso Supletivo de Guitarra",
    "Curso Básico de Harpa",
    "Curso Supletivo de Harpa",
    "Curso Básico de Oboé",
    "Curso Supletivo de Oboé",
    "Curso Básico de Orgão",
    "Curso Supletivo de Orgão",
    "Curso Básico de Percussão",
    "Curso Supletivo de Percussão",
    "Curso Básico de Piano",
    "Curso Supletivo de Piano",
    "Curso Básico de Saxofone",
    "Curso Supletivo de Saxofone",
    "Curso Básico de Trombone",
    "Curso Supletivo de Trombone",
    "Curso Básico de Trompa",
    "Curso Supletivo de Trompa",
    "Curso Básico de Trompete",
    "Curso Supletivo de Trompete",
    "Curso Básico de Tuba",
    "Curso Supletivo de Tuba",
    "Curso Básico de Violoncelo",
    "Curso Supletivo de Violoncelo",
    "Curso Básico de Violino",
    "Curso Supletivo de Violino",
    "Curso Básico de Viola de Arco",
    "Curso Supletivo de Viola de Arco",
    "Curso Básico de Bandolim",
    "Curso Supletivo de Bandolim",
    ];
        