
            var ids= ["A1510",
    "A32597",
    "A36539",
    "A38165",
    "A38176",
    "A38196",
    "A35271",
    "A38193",
    "A18141",
    "A38218",
    "A36487",
    "A35272",
    "A27589",
    "A25073",
    "A38169",
    "A33822",
    "A38214",
    "A35274",
    "A29871",
    "A38215",
    "A38117",
    "A35277",
    "A35278",
    "A38138",
    "A35280",
    "A33057",
    "A38143",
    "A30166",
    "A36971",
    "A38132",
    "A33140",
    "A33141",
    "A33291",
    "A33142",
    "A20044",
    "A35283",
    "A35284",
    "A38156",
    "A35285",
    "A36422",
    "A33143",
    "A33145",
    "A33146",
    "A33148",
    "A38124",
    "A30176",
    "A35808",
    "A38126",
    "A33689",
    "A38125",
    "A24654",
    "A20021",
    "A35291",
    "A34640",
    "A38207",
    "A32010",
    "A35052",
    "A35440",
    "A32648",
    "A33152",
    "A38211",
    "A38210",
    "A22854",
    "A35293",
    "A35294",
    "A38166",
    "A38164",
    "A38167",
    "A33155",
    "A35298",
    "A38190",
    "A35300",
    "A30305",
    "A36757",
    "A33157",
    "A27608",
    "A35302",
    "A33158",
    "A35465",
    "A33858",
    "A26737",
    "A30187",
    "A35303",
    "A36445",
    "A38595",
    "A38187",
    "A36424",
    "A35308",
    "A35443",
    "A27616",
    "A38163",
    "A39288",
    "A33162",
    "A35311",
    "A39508",
    "A33163",
    "A38174",
    "A33165",
    "A35312",
    "A38185",
    "A39503",
    "A36758",
    "A38197",
    "A33272",
    "A35315",
    "A38202",
    "A35316",
    "A35395",
    "A38204",
    "A26208",
    "A33703",
    "A38134",
    "A35318",
    "A33168",
    "A35319",
    "A35320",
    "A32753",
    "A38180",
    "A35321",
    "A35322",
    "A38133",
    "A30201",
    "A38123",
    "A34935",
    "A35323",
    "A33172",
    "A38191",
    "A38186",
    "A39750",
    "A22662",
    "A35325",
    "A17855",
    "A38175",
    "A33173",
    "A39622",
    "A33175",
    "A18938",
    "A33176",
    "A35832",
    "A38170",
    "A36425",
    "A38212",
    "A38220",
    "A38199",
    "A38198",
    "A35328",
    "A38157",
    "A20464",
    "A38139",
    "A35330",
    "A16409",
    "A33709",
    "A30209",
    "A21008",
    "A35331",
    "A38189",
    "A19705",
    "A30211",
    "A30212",
    "A36960",
    "A34434",
    "A35332",
    "A39506",
    "A36761",
    "A38224",
    "A35333",
    "A23916",
    "A38222",
    "A38205",
    "A27629",
    "A38206",
    "A35398",
    "A32480",
    "A30213",
    "A22670",
    "A33182",
    "A28722",
    "A38121",
    "A35334",
    "A38136",
    "A35335",
    "A35337",
    "A38142",
    "A38140",
    "A38137",
    "A38128",
    "A30214",
    "A23508",
    "A38155",
    "A35843",
    "A38150",
    "A34035",
    "A24839",
    "A35339",
    "A35340",
    "A33650",
    "A35342",
    "A38223",
    "A39341",
    "A39408",
    "A33186",
    "A38219",
    "A29631",
    "A39747",
    "A33188",
    "A38172",
    "A38168",
    "A38254",
    "A30219",
    "A35348",
    "A27637",
    "A29004",
    "A35349",
    "A35350",
    "A39406",
    "A29011",
    "A38178",
    "A38152",
    "A38179",
    "A22685",
    "A22688",
    "A36864",
    "A38184",
    "A12753",
    "A38161",
    "A38171",
    "A38194",
    "A23544",
    "A29048",
    "A36454",
    "A35352",
    "A38217",
    "A38209",
    "A30226",
    "A38221",
    "A21432",
    "A39342",
    "A32608",
    "A33195",
    "A22695",
    "A38216",
    "A33196",
    "A33420",
    "A38195",
    "A33727",
    "A33127",
    "A24784",
    "A38208",
    "A38203",
    "A15619",
    "A35355",
    "A33437",
    "A22701",
    "A27645",
    "A29282",
    "A38120",
    "A14539",
    "A33280",
    "A34508",
    "A27577",
    "A39938",
    "A33204",
    "A38122",
    "A35357",
    "A30238",
    "A39407",
    "A33209",
    "A36476",
    "A35360",
    "A21711",
    "A32652",
    "A36969",
    "A33213",
    "A30241",
    "A33214",
    "A38116",
    "A35144",
    "A38118",
    "A27658",
    "A38159",
    "A35363",
    "A25383",
    "A35364",
    "A33524",
    "A35855",
    "A38147",
    "A33281",
    "A30243",
    "A38149",
    "A38160",
    "A33082",
    "A38154",
    "A38158",
    "A30015",
    "A39509",
    "A38153",
    "A38151",
    "A38129",
    "A33222",
    "A38130",
    "A34435",
    "A19550",
    "A35366",
    "A22721",
    "A30254",
    "A18770",
    "A38141",
    "A38200",
    "A36764",
    "A38135",
    "A39944",
    "A38148",
    "A33228",
    "A38146",
    "A38908",
    "A35371",
    "A24875",
    "A37029",
    "A33229",
    "A38119",
    "A24876",
    "A29253",
    "A25868",
    "A28735",
    "A27673",
    "A35372",
    "A33234",
    "A36765",
    "A38173",
    "A38183",
    "A33235",
    "A39343",
    "A39410",
    "A35374",
    "A24885",
    "A38177",
    "A35375",
    "A38181",
    "A33238",
    "A35376",
    "A38131",
    "A33240",
    "A38144",
    "A38145",
    "A29254",
    "A35418",
    "A38127",
    "A33282",
    "A30266",
    "A35377",
    "A38192",
    "A35378",
    "A38182",
    "A36773",
    "A39671",
    "A27648",
    "A27620",
    "A33199",
    "AE-939",
    "AE-922",
    "AE-907",
    "A1",
    ];
            var nomes=["ADEMAR FONTES DE MAGALHAES GONCALVES",
    "ADERITO NELSON MIRANDA DE OLIVEIRA",
    "ADMILSON CESAR ANDRADE RODRIGUES",
    "AFONSO DELERUE ARRIAGA",
    "AGOSTINHO MANUEL ALVES DA SILVA",
    "ALEXANDRE COELHO CARVALHO",
    "ALEXANDRE JORGE CAMELO FARIA",
    "ALEXANDRE MANUEL PEREIRA DE MIRANDA PINTO",
    "ALEXANDRE MIGUEL DA COSTA FERREIRA DOS SANTOS",
    "ALEXANDRINA MARIA FERREIRA LEMOS",
    "ALI DOS REIS MOTA",
    "ANA LUISA PARREIRA NUNES",
    "ANA MARGARIDA FIDALGO PINHEIRO",
    "ANA MARGARIDA LIMA ALEM",
    "ANDRE ABILIO NUNES ROCHA RODRIGUES",
    "ANDRE FERNANDES MARTINS",
    "ANDRE FILIPE DE SOUSA VIVEIROS",
    "ANDRE FILIPE OLIVEIRA MARTINS",
    "ANDRE LEITE FERREIRA",
    "ANDRE RIBEIRO RODRIGUES",
    "ANTONIO ANDRE MARQUES RIBEIRO",
    "ANTONIO MANUEL MARTINS PINTO",
    "ANTONIO MANUEL RODRIGUES FERNANDES",
    "ANTONIO NUNO BACELAR MARTINS BARREIRO COVAS",
    "ANTONIO RICARDO PEREIRA GONCALVES",
    "ANTONIO RUI MIRANDA DE LEMOS",
    "ANTONIO SERGIO MATOS SILVA",
    "ANTONIO TIAGO MORGADO PEREIRA",
    "AUGUSTO JORGE PEREIRA DA COSTA",
    "AVELINO JOSE DA COSTA REGO",
    "AVELINO RODRIGO ARAUJO SEMELHE DE SOUSA PINTO",
    "BARBARA ALEXANDRA EUSEBIO FREITAS",
    "BARBARA SOFIA ARAUJO DA SILVA",
    "BRUNO CESAR PEREIRA DA SILVA",
    "BRUNO DE ALMEIDA RAMOS PEREIRA",
    "BRUNO EDGAR BERNARDO TEIXEIRA",
    "BRUNO EMANUEL TEIXEIRA DE CASTRO ARAUJO",
    "BRUNO FILIPE DA COSTA HERMENEGILDO",
    "BRUNO GABRIEL LEAL MACHADO DOS SANTOS",
    "BRUNO JOSE DE MACEDO SOARES AMOR",
    "BRUNO MIGUEL CAMPOS RODRIGUES",
    "BRUNO MIGUEL FLORES DIAMANTINO",
    "BRUNO MIGUEL MAGALHAES AZEVEDO",
    "BRUNO MIGUEL TEIXEIRA PAIVA DE FARIA",
    "BRUNO RICARDO CUNHA MAGALHAES",
    "BRUNO RICARDO DUARTE MAGALHAES",
    "CANDIDO MIGUEL REBELO BARROS",
    "CARLOS ALFREDO MACIEIRA DE FARIA",
    "CARLOS ANDRE BRITO RIBEIRO",
    "CARLOS CESAR MADUREIRA ROMANO",
    "CARLOS DE SOUSA CABRAL BRANDAO",
    "CARLOS JOSE DA CUNHA RIBEIRO",
    "CARLOS MIGUEL TAVARES LOPES",
    "CARLOS PRUDENCIO DO ESPIRITO CRISOSTOMO",
    "CATARINA ISABEL DE OLIVEIRA MATEUS",
    "CATARINA SOFIA MARTINHO LUIS",
    "CESAR FILIPE DA CRUZ GOMES",
    "DANIEL BARBOSA ALVES",
    "DANIEL FILIPE PERES FERREIRA",
    "DANIEL RICARDO DE CASTRO MENDES",
    "DANIEL TORRES GONCALVES",
    "DANIELA CRISTINA GARCIA TEIXEIRA",
    "DAVI CARNEIRO PEREIRA",
    "DAVID DANIEL CARDOSO DE OLIVEIRA",
    "DIAMANTINO JOSE MADEIRA ABOBELEIRA",
    "DIOGO FILIPE DA SILVA CARDOSO",
    "DIOGO PAULO DA FONTE LAPA",
    "DUARTE ALEXANDRE DA CUNHA ALVES",
    "DUARTE FILIPE AFONSO CHAVES",
    "DUARTE NUNO MALHEIRO DE BARREIRO",
    "ELISEU CARNEIRO DOS SANTOS ROCHA",
    "EMANUEL CERDEIRA MESQUITA",
    "EMANUEL JOSE ANTUNES FERNANDES",
    "ERNESTO MANUEL DA SILVA LOPES",
    "EURICO MANUEL FOLGADO AFONSO",
    "EURICO MANUEL TELES MORAIS",
    "FABIO ROBERTO LEITE MATOS",
    "FAUSTO MIGUEL PACHECO FARIA VIANA",
    "FERNANDO ANTONIO ALVES LOPES",
    "FERNANDO JORGE PINTO LIMA",
    "FERNANDO MIGUEL SOUSA LISBOA",
    "FERNANDO SERGIO MADALENO PEREIRA",
    "FILIPE ANTONIO GONCALVES DA SILVA",
    "FILIPE BARROSO DE OLIVEIRA",
    "FILIPE GONCALO GONCALVES DA COSTA",
    "FLAVIO MIGUEL XAVIER FERREIRA",
    "FRANCISCO EURICO PINTO CORTEZ MARTINS LEITE",
    "FRANCISCO JOSE MAIO LEITE",
    "FRANCISCO JOSE MARTINS GOMES",
    "FRANCISCO JOSE PRATA DA PAZ",
    "GASPAR AUGUSTO SIMOES CORREIA VIEIRA LEITE",
    "GENILDO SOARES NEVES",
    "GONCALO LEAL MACHADO RIBEIRO PINTO",
    "GONCALO LUIS MALHEIRO DE OLIVEIRA NOVAIS MACHADO",
    "GONCALO MANUEL CORREIA CALHEIROS",
    "GONCALO PAULO CUNHA CARDOSO FERREIRA",
    "GUILHERME REIS BARBOSA",
    "HELDER ARTUR PEIXOTO MAGALHAES",
    "HELDER FILIPE DE CASTRO MARQUES",
    "HELDER JOSE FERREIRA BARBOSA RIBEIRO",
    "HELDER NUNO MARTINS DO VALE TOME",
    "HUGO ALEXANDRE PEREIRA TRIUNFANTE MARTINS",
    "HUGO ALEXANDRE SOBREIRO DE SEIXAS",
    "HUGO ANDRE PEIXOTO FREITAS PEREIRA",
    "HUGO EMANUEL QUEIROS TEIXEIRA DA SILVA",
    "HUGO FILIPE NASCIMENTO PEREIRA",
    "HUGO GUILHERME DOS SANTOS RIGOR",
    "HUGO JOSE FERNANDES CARVALHO",
    "HUGO JOSE PEREIRA PACHECO",
    "IGOR MURILO DE ALMEIDA",
    "ISABEL MARIA ROSENDO CARDOSO",
    "IVO MANUEL DANTAS MONTEIRO",
    "JASON PETER COSTA",
    "JOANA SOUTO DE MIRANDA GONZALEZ",
    "JOAO ALEXANDRE VAZ OLIVEIRA",
    "JOAO ANTONIO LAVRADOR VILANOVA",
    "JOAO ARNALDO FREITAS DE ABREU",
    "JOAO CARLOS AZEVEDO SALGADO GUIMARAES",
    "JOAO FILIPE FONTES MACHADO",
    "JOAO GILBERTO LAMARAO DA SILVA",
    "JOAO GONCALO BOTICA RIBEIRO DA SILVA",
    "JOAO GUILHERME RABACA CAMPOS",
    "JOAO MANUEL DA SILVA SANCHES",
    "JOAO MANUEL DE CAMPOS GONCALVES",
    "JOAO MARIO MENDES DE OLIVEIRA",
    "JOAO MIGUEL RAPOSO DA SILVA MARQUES",
    "JOAO MIGUEL RODRIGUES BATISTA",
    "JOAO NUNO MARQUES DOS SANTOS",
    "JOAO PAULO BARBOSA OLIVEIRA",
    "JOAO PAULO CARRAPATO ALMEIDA",
    "JOAO PAULO COELHO GOMES TEIXEIRA E OLIVEIRA",
    "JOAO PAULO DA SILVA CASTRO",
    "JOAO PAULO DA SILVA GOMES",
    "JOAO PAULO MINHAVA PEIXOTO ASSIS CARDOSO",
    "JOAO PAULO SILVA DE VASCONCELOS GUSMAO",
    "JOAO PEDRO BACAO COELHO DE BARROS",
    "JOAO PEDRO BRITO ANTUNES GUIMARAES",
    "JOAO PEDRO GOMES FERNANDES",
    "JOAO PEDRO GONCALVES DE CARVALHO",
    "JOAO PEDRO OLIVEIRA PEREIRA",
    "JOAO PEDRO ROBALO ESPINHO PEREIRA DA SILVA",
    "JOAO PEDRO SILVA ARAUJO",
    "JOAO RAFAEL FERREIRA VELOSO",
    "JOAO RICARDO DA SILVA CAMPOS",
    "JOAQUIM MACHADO GONCALVES SAMPAIO",
    "JOEL ARAUJO ROCHA",
    "JOEL HUMBERTO DA SILVA BEIRAO DO VALE CARVALHO",
    "JOEL TITO DA CRUZ PINTO",
    "JORGE ALBERTO FARIA MIRANDA",
    "JORGE ANDRE ALVES DE MELO",
    "JORGE MANUEL DE CASTRO MAIO GOMES DA COSTA",
    "JORGE MANUEL VIANA RIBEIRO MARTINS FORTE",
    "JORGE MIGUEL GONCALVES DA SILVA",
    "JORGE MIGUEL SILVA MELO PEREIRA",
    "JOSE ALEXANDRE DE CARVALHO AMORIM",
    "JOSE ANTONIO DA CUNHA E SILVA",
    "JOSE ANTONIO PEREIRA CIBRAO",
    "JOSE CARLOS CARVALHO DOS SANTOS",
    "JOSE CARLOS DA ROCHA MACHADO",
    "JOSE CARLOS DE FREITAS FONTAO",
    "JOSE CARLOS MARQUES DIAS",
    "JOSE DIOGO RIBEIRO LIZ DE ALMEIDA",
    "JOSE EDUARDO CORREIA CALHEIROS",
    "JOSE EDUARDO TEIXEIRA RITO",
    "JOSE FILIPE HENRIQUES VILAS BOAS",
    "JOSE FILIPE QUEIJO FERNANDES",
    "JOSE GRACA DA NOBREGA",
    "JOSE LUIS CARDOSO SILVA",
    "JOSE LUIS LOPES DE ARAUJO",
    "JOSE LUIS PINTO MONTEIRO ALVES",
    "JOSE MANUEL ARAUJO SOARES",
    "JOSE MANUEL ESTEVES",
    "JOSE MANUEL LIMA GANDARELA",
    "JOSE MANUEL LOUREIRO DE AZEVEDO TEIXEIRA",
    "JOSE MANUEL TEIXEIRA FERNANDES",
    "JOSE MIGUEL DOS SANTOS FERRAZ",
    "JOSE MIGUEL FERREIRA PONTES",
    "JOSE MIGUEL RODRIGUES OLIVEIRA DA SILVA",
    "JOSE MIGUEL SILVA PEIXOTO DE CARVALHO",
    "JOSE NUNO MARTINS PINTO FRAGA",
    "JOSE PAULO CARNEIRO DE MELO MAMEDE",
    "JOSE PEDRO DOMINGUES",
    "JOSE PEDRO FARIA E VASCONCELOS CORREIA",
    "JOSE PEDRO MACHADO GOMES",
    "JOSE PEDRO RIBEIRO DA ARAUJO",
    "JOSE PEDRO RODRIGUES MAGALHAES",
    "JOSE PEDRO SILVA DE OLIVEIRA CARVALHO",
    "JOSE ROMEU FERNANDES PINTO",
    "JULIO ANDRE RODRIGUES ARAUJO",
    "LARA SOFIA ALPOIM MIRANDA",
    "LEANDRO EMANUEL DA SILVA SALGADO BARBOSA",
    "LEONOR ISABEL CONSTANTINO CAEIRO BOGA",
    "LEONOR ISABEL FERREIRA DE MELO OSORIO ARAUJO",
    "LIDIA NOGUEIRA LARANJEIRA",
    "LILIANA SOLANGE SEQUEIRA HENRIQUES DE MACEDO",
    "LUIS ANDRE DA CUNHA MARQUES",
    "LUIS CARLOS GONCALO LEONARDO",
    "LUIS DIOGO MONTEIRO DUARTE COUTO",
    "LUIS FERNANDO ROMANEL RODRIGUES",
    "LUIS FILIPE FARIA MONTEIRO CAPELO",
    "LUIS FILIPE GAMA PAIS CABRAL",
    "LUIS FILIPE PEREIRA GONCALVES",
    "LUIS FILIPE RIBEIRO NOVAIS",
    "LUIS PEDRO FERREIRA LEITE DOS SANTOS ALEIXO",
    "LUIS PEDRO LOPES PEREIRA",
    "LUIS TIAGO AFONSO MASCARENHAS",
    "LUIZ ALBERTO DE CASTRO SANTOS",
    "MANUEL DOMINGOS DE CARVALHO FELGUEIRAS DA SILVA SANTOS",
    "MANUEL FERNANDO SOTO MAIOR FRANQUEIRA",
    "MANUEL JOSE GOMES MEIRELES",
    "MANUEL JOSE TORRES SOUSA DA CUNHA",
    "MARANGAZE JOAQUIM MUNHEPE MULHANGA",
    "MARCIA MARLENE DE ALMEIDA MARTINS",
    "MARCIAL COELHO GOMES",
    "MARCO ALEXANDRE AGUIAR VAZ",
    "MARCO ALEXANDRE BARREIRA MEDEIROS TEIXEIRA",
    "MARCO ALEXANDRE TEIXEIRA PALOS",
    "MARCO ANTONIO SAMPAIO FREITAS DE CASTRO",
    "MARCO ANTONIO TEIXEIRA MARTINS",
    "MARCO FRANCISCO DA SILVA LIZARDO",
    "MARCO RICARDO BARBOSA COELHO",
    "MARIA BEATRIZ ALVES DE SA CAMPOS",
    "MARIA CRISTINA CARNEIRO BARREIRA",
    "MARIA LUISA VILLAVERDE MACHADO FERNANDES NOVAIS",
    "MARIANA PEREIRA NEVES",
    "MARIO ANDRE PATRICIO TEIXEIRA JULIO",
    "MARIO DA FONTE LAMEIRAS",
    "MARIO RUI ANUNCIACAO MONTEIRO",
    "MARIO RUI RIBEIRO FIALHO DA CONCEICAO",
    "MICHEL FERREIRA PINTO",
    "MIGUEL AFONSO PIRES DA ROSA",
    "MIGUEL ANGELO MARQUES DE MATOS",
    "MIGUEL ANGELO PINTO MARQUES",
    "MIGUEL ANGELO RIBEIRO DE SOUSA E SILVA",
    "MIGUEL ANGELO VIVAS GOMES ALVES",
    "MIGUEL MANUEL GOMES RODRIGUES",
    "MIGUEL PEDRO AMARAL FIGUEIREDO",
    "MIGUEL PEDRO DE ALMEIDA FERREIRA CORREIA DOURADO",
    "MIGUEL PINTO DE SOUSA MARQUES",
    "NANCY DO SAMEIRO SILVERIO LAVANDEIRA",
    "NELSON DE SOUSA E SILVA",
    "NELSON FILIPE COELHO DE MOURA SOUSA",
    "NELSON LEANDRO BARBOSA CARNEIRO",
    "NELSON TAVARES CUNHA",
    "NUNO FILIPE ANTUNES DA SILVA",
    "NUNO FILIPE MAGALHAES SANTOS",
    "NUNO FILIPE MARQUES MOREIRA RIBEIRO",
    "NUNO GONCALO BETTENCOURT DA CRUZ CORREIA",
    "NUNO JORGE FERREIRA GUIMARAES",
    "NUNO MIGUEL AFONSO CARVALHO DE MOURA",
    "NUNO MIGUEL MACHADO ALVES COSTA",
    "NUNO MIGUEL MARQUES GOMES",
    "NUNO MIGUEL MARTINS CASANOVA",
    "NUNO MIGUEL OLIVEIRA SILVA",
    "NUNO VIRIATO MACEDO FERREIRA DE CARVALHO",
    "OCTAVIO DAVID DA CONCEICAO JACINTO",
    "ORLANDO JORGE GONCALVES PINTO",
    "PAULO BRUNO DA SILVA VIDES FERNANDES",
    "PAULO CESAR ALMEIDA DE SA",
    "PAULO CESAR DE CARVALHO LOPES",
    "PAULO CESAR ROMANEL RODRIGUES",
    "PAULO EDUARDO MIRANDA CAMPOS",
    "PAULO JORGE ASSIS DE SOUSA",
    "PAULO JORGE FERNANDES DE SOUSA",
    "PAULO JORGE SOARES MENDES",
    "PAULO MANUEL RIBEIRO NOVAIS",
    "PAULO MIGUEL SA MORAIS PIRES",
    "PEDRO ALEXANDRE FERREIRA VILACA",
    "PEDRO DANIEL FERREIRA DE CARVALHO",
    "PEDRO DAVID ALVES MARTINHO",
    "PEDRO DUARTE CARDOSO LOPES",
    "PEDRO EMANUEL FERNANDES LOPES",
    "PEDRO GUIMARAES DE FREITAS",
    "PEDRO HENRIQUE GONCALVES GERAZ RODRIGUES",
    "PEDRO JORGE OSORIO MARINHO OLIVEIRA",
    "PEDRO JOSE MARTINS FARIA",
    "PEDRO MANUEL DE AMORIM MAGALHAES",
    "PEDRO MANUEL LOPES PATRICIO",
    "PEDRO MIGUEL ARAUJO MOTA LOPES",
    "PEDRO MIGUEL AZEVEDO DE OLIVEIRA",
    "PEDRO MIGUEL DA SILVA ARAUJO",
    "PEDRO MIGUEL MARTINS FERNANDES",
    "PEDRO MIGUEL MEIRA DAS NEVES",
    "PEDRO MIGUEL PAES MACHADO",
    "PEDRO MIGUEL PINTO RIBEIRO",
    "PEDRO MIGUEL RAMOS MADEIRA",
    "PEDRO MIGUEL SOARES PINTO",
    "PEDRO MIGUEL VEIGA DA SILVA",
    "PEDRO SILVESTRE MENESES MAGALHAES COELHO",
    "PEDRO TIAGO AMORIM DE BRITO",
    "PEDRO TIAGO DIAS GONCALVES",
    "RAFAEL DE CASTRO CARREIRA",
    "RAUL GRACIANO OLIVEIRA RODRIGUES",
    "RENATO CESAR ALMEIDA FIGUEIREDO",
    "RICARDO ANDRE RODRIGUES AFONSO",
    "RICARDO ARAUJO CARVALHO VILACA MOREIRA",
    "RICARDO FERNANDO LIRA DE MESQUITA LACHADO",
    "RICARDO GOMES DE FARIA",
    "RICARDO JORGE ALMEIDA DE MAGALHAES",
    "RICARDO JORGE RODRIGUES SEPULVEDA MARQUES",
    "RICARDO JOSE FERREIRA DIAS DE OLIVEIRA",
    "RICARDO MANUEL RODRIGUES DE OLIVEIRA DIMAS",
    "RICARDO MANUEL VIANA MAGALHAES",
    "RICARDO NUNO MOREIRA CASTILHO FERREIRA LOPES",
    "ROQUE MANUEL DE CARVALHO TEIXEIRA",
    "ROSA ALEXANDRA AZEVEDO GUIMARAES",
    "RUBEN FILIPE CARDOSO DA FONSECA",
    "RUI ALEXANDRE SERRANO DE MOURA",
    "RUI ANDRE FERREIRA SILVA",
    "RUI ANDRE LEITE RIBEIRO",
    "RUI ANTONIO PEIXOTO DE ABREU",
    "RUI DOMINGOS GUIMARAES SALGADO",
    "RUI FILIPE BARROS TAVARES",
    "RUI FILIPE TORRES ALEXANDRE",
    "RUI JORGE DE OLIVEIRA PEREIRA",
    "RUI JORGE GUIMARAES MACHADO RODRIGUES VALENTE",
    "RUI MANUEL COUTO DA SILVA",
    "RUI MANUEL DA SILVA PEREIRA NEIVA",
    "RUI MANUEL SILVA OLIVEIRA",
    "RUI MIGUEL DA SILVA ABREU",
    "RUI MIGUEL ESCUDEIRO DA COSTA AGUIAR",
    "RUI MIGUEL FERNANDES VARELA",
    "RUI MIGUEL MORAIS LOPES",
    "RUI MIGUEL NOVAIS CASTRO",
    "RUI MIGUEL PEREIRA OLIVEIRA",
    "RUI PEDRO ANDIAS DUARTE",
    "SANDRA MARIA OLIVEIRA CARVALHO",
    "SANDRA MARIA TELES FEIO ALMEIDA FAZENDEIRO",
    "SEBASTIAO MONTEIRO SIMOES",
    "SERGIO BRANCO AMORIM",
    "SERGIO DE ALMEIDA PAIVA",
    "SERGIO FELICIANO FERREIRA JACOME",
    "SERGIO FILIPE PEREIRA DA FELICIDADE",
    "SERGIO MANUEL PEREIRA BARREIRO",
    "SERGIO MANUEL RUIVO CARDOSO",
    "SERGIO NUNO CLARO GOMES",
    "SERGIO RICARDO TEIXEIRA ANDIAS MIRANDA",
    "SOFIA DA CONCEICAO ALVES MENDES",
    "SONIA ANDREA GARRIDO DE SA EIRAS",
    "TELMA DE FATIMA PIRES DE SA",
    "TIAGO DANIEL CERQUEIRA BOTELHO DA SILVA",
    "TIAGO JORGE GOMES DA SILVA ARAUJO",
    "TIAGO LEANDRO DE CASTRO RIBEIRO",
    "TIAGO MIGUEL SOARES FERNANDES",
    "TITO JOSE FERREIRA DE SOUSA LOPES",
    "VALTER MIGUEL OLIVEIRA VILAR",
    "VANESSA ALZIRA ABRUNHOSA CARNEIRO DE CASTRO FIDALGO",
    "VIRGILIO ABRANTES VINHA",
    "VITOR CARLOS TEIXEIRA PIMENTEL",
    "VITOR DA COSTA PINHEIRO",
    "VITOR HUGO DA SILVA NOGUEIRA",
    "VITOR HUGO PEREIRA DA SILVA MOREIRA",
    "VITOR MANUEL ALVES DA ROCHA",
    "VITOR MANUEL CARVALHO RODRIGUES",
    "VITOR MANUEL PINTO LOPES",
    "NUNO RAMOS MATOS",
    "JOAO ANDRE FARIA LOPES",
    "NUNO FILIPE MENDES PEREIRA",
    "Jorge Gonzalez y Hurtado de Mendoza",
    "Brais Hernandez Facal",
    "Oscar Lopez Garcia",
    "Eusébio da Silva Ferreira",
    ];
            var instrumentos = ["Contrabaixo",
    "Flauta",
    "Guitarra",
    "Violino",
    "Contrabaixo",
    "Contrabaixo",
    "Guitarra",
    "Guitarra",
    "Piano",
    "Violoncelo",
    "Piano",
    "Violoncelo",
    "Fliscorne",
    "Oboé",
    "Eufónio",
    "Viola de Arco",
    "Flauta",
    "Oboé",
    "Viola de Arco",
    "Saxofone",
    "Saxofone",
    "Violoncelo",
    "Trombone",
    "Viola de Arco",
    "Guitarra",
    "Contrabaixo",
    "Tuba",
    "Bandolim",
    "Flauta",
    "Flauta",
    "Contrabaixo",
    "Trompete",
    "Fliscorne",
    "Trompete",
    "Violoncelo",
    "Orgão",
    "Violino",
    "Corne Inglês",
    "Orgão",
    "Contrabaixo",
    "Guitarra",
    "Fagote",
    "Harpa",
    "Oboé",
    "Violoncelo",
    "Trompa",
    "Saxofone",
    "Trombone",
    "Fagote",
    "Contrabaixo",
    "Tuba",
    "Guitarra",
    "Guitarra",
    "Saxofone",
    "Flauta",
    "Violino",
    "Tuba",
    "Percussão",
    "Guitarra",
    "Trompete",
    "Violoncelo",
    "Piano",
    "Eufónio",
    "Piano",
    "Clarinete",
    "Piano",
    "Bandolim",
    "Bandolim",
    "Flauta",
    "Fliscorne",
    "Piano",
    "Flauta",
    "Harpa",
    "Violino",
    "Guitarra",
    "Bandolim",
    "Trompete",
    "Percussão",
    "Fliscorne",
    "Viola de Arco",
    "Percussão",
    "Violoncelo",
    "Harpa",
    "Trombone",
    "Guitarra",
    "Eufónio",
    "Percussão",
    "Harpa",
    "Eufónio",
    "Trompa",
    "Trombone",
    "Tuba",
    "Orgão",
    "Flauta",
    "Corne Inglês",
    "Guitarra",
    "Contrabaixo",
    "Guitarra",
    "Saxofone",
    "Violino",
    "Bandolim",
    "Flauta",
    "Guitarra",
    "Orgão",
    "Percussão",
    "Viola de Arco",
    "Trombone",
    "Flauta",
    "Fagote",
    "Oboé",
    "Trompa",
    "Fagote",
    "Flauta",
    "Violoncelo",
    "Harpa",
    "Trombone",
    "Percussão",
    "Trombone",
    "Guitarra",
    "Eufónio",
    "Tuba",
    "Flauta",
    "Contrabaixo",
    "Contrabaixo",
    "Fliscorne",
    "Trombone",
    "Harpa",
    "Corne Inglês",
    "Fagote",
    "Clarinete",
    "Trompa",
    "Oboé",
    "Trompa",
    "Guitarra",
    "Fagote",
    "Corne Inglês",
    "Violino",
    "Trompa",
    "Contrabaixo",
    "Eufónio",
    "Corne Inglês",
    "Trompa",
    "Trompete",
    "Fliscorne",
    "Clarinete",
    "Clarinete",
    "Contrabaixo",
    "Percussão",
    "Trombone",
    "Harpa",
    "Tuba",
    "Flauta",
    "Saxofone",
    "Orgão",
    "Harpa",
    "Contrabaixo",
    "Viola de Arco",
    "Violino",
    "Guitarra",
    "Bandolim",
    "Harpa",
    "Violoncelo",
    "Harpa",
    "Orgão",
    "Fliscorne",
    "Bandolim",
    "Trompa",
    "Corne Inglês",
    "Viola de Arco",
    "Saxofone",
    "Saxofone",
    "Corne Inglês",
    "Saxofone",
    "Corne Inglês",
    "Bandolim",
    "Contrabaixo",
    "Flauta",
    "Orgão",
    "Orgão",
    "Bandolim",
    "Orgão",
    "Trompa",
    "Corne Inglês",
    "Piano",
    "Clarinete",
    "Contrabaixo",
    "Trompete",
    "Trombone",
    "Violino",
    "Viola de Arco",
    "Trombone",
    "Piano",
    "Trompete",
    "Violino",
    "Harpa",
    "Clarinete",
    "Contrabaixo",
    "Clarinete",
    "Tuba",
    "Trompa",
    "Trompete",
    "Corne Inglês",
    "Percussão",
    "Tuba",
    "Oboé",
    "Guitarra",
    "Fliscorne",
    "Fagote",
    "Percussão",
    "Saxofone",
    "Violoncelo",
    "Bandolim",
    "Bandolim",
    "Harpa",
    "Percussão",
    "Saxofone",
    "Viola de Arco",
    "Oboé",
    "Fliscorne",
    "Corne Inglês",
    "Fagote",
    "Harpa",
    "Oboé",
    "Guitarra",
    "Violino",
    "Violoncelo",
    "Trompete",
    "Fliscorne",
    "Violino",
    "Eufónio",
    "Fliscorne",
    "Tuba",
    "Oboé",
    "Violino",
    "Flauta",
    "Harpa",
    "Fagote",
    "Violino",
    "Contrabaixo",
    "Guitarra",
    "Clarinete",
    "Tuba",
    "Oboé",
    "Harpa",
    "Eufónio",
    "Orgão",
    "Violino",
    "Clarinete",
    "Violino",
    "Fliscorne",
    "Trombone",
    "Harpa",
    "Eufónio",
    "Harpa",
    "Flauta",
    "Flauta",
    "Orgão",
    "Flauta",
    "Contrabaixo",
    "Trompete",
    "Fliscorne",
    "Trompete",
    "Flauta",
    "Fagote",
    "Bandolim",
    "Saxofone",
    "Violino",
    "Contrabaixo",
    "Eufónio",
    "Corne Inglês",
    "Viola de Arco",
    "Saxofone",
    "Percussão",
    "Trompete",
    "Eufónio",
    "Eufónio",
    "Corne Inglês",
    "Piano",
    "Tuba",
    "Trompa",
    "Trompete",
    "Clarinete",
    "Orgão",
    "Harpa",
    "Flauta",
    "Clarinete",
    "Orgão",
    "Viola de Arco",
    "Violino",
    "Fliscorne",
    "Violino",
    "Eufónio",
    "Trompete",
    "Viola de Arco",
    "Violoncelo",
    "Violoncelo",
    "Violino",
    "Piano",
    "Oboé",
    "Fagote",
    "Eufónio",
    "Oboé",
    "Trombone",
    "Fagote",
    "Oboé",
    "Orgão",
    "Flauta",
    "Violino",
    "Clarinete",
    "Piano",
    "Violoncelo",
    "Viola de Arco",
    "Tuba",
    "Piano",
    "Trompete",
    "Tuba",
    "Trompa",
    "Contrabaixo",
    "Guitarra",
    "Percussão",
    "Trompete",
    "Fagote",
    "Fliscorne",
    "Tuba",
    "Harpa",
    "Oboé",
    "Fagote",
    "Trombone",
    "Viola de Arco",
    "Fagote",
    "Trompa",
    "Trompete",
    "Contrabaixo",
    "Fliscorne",
    "Viola de Arco",
    "Fliscorne",
    "Flauta",
    "Viola de Arco",
    "Tuba",
    "Corne Inglês",
    "Corne Inglês",
    "Trombone",
    "Piano",
    "Violoncelo",
    "Fagote",
    "Fliscorne",
    "Eufónio",
    "Corne Inglês",
    "Harpa",
    "Clarinete",
    "Fagote",
    "Orgão",
    "Violino",
    "Piano",
    "Guitarra",
    "Fliscorne",
    "Violoncelo",
    "Violino",
    "Contrabaixo",
    "Harpa",
    "Clarinete",
    "Clarinete",
    ];
        